### ISSUE TITLE
Create different portfolio websites

### ISSUE THREAD

**Issue by sonalikari** [sonalikari/HacktoberFest--2022#1]

**Comment by Vidhika002** [comment]
Hi Please assign me this task

**Comment by sonalikari** [comment]
@Vidhika002 Go ahead.

**Comment by Anish-Parkhi** [comment]
I can work on this issue.

**Comment by sonalikari** [comment]
@Anish-Parkhi yes, you can work.

**Comment by hansupadhyay007** [comment]
I can work on this issue.

**Comment by sonalikari** [comment]
@hansupadhyay007 yes, you can work.

**Comment by Arvind0-0** [comment]
hello @sonalikari  i want to work on this project please assigned it to me

**Comment by sonalikari** [comment]
Hey @Arvind0-0, you can work on this project by creating PR.

**Comment by E-fais** [comment]
I would like to work on this.

**Comment by YashGadia** [comment]
@sonalikari Can I work on this issue?

**Comment by sonalikari** [comment]
@YashGadia Yes, you can work.
