### ISSUE TITLE
Add live demo

### ISSUE THREAD

**Issue by E-fais** [sonalikari/HacktoberFest--2022#34]
If contributors deploy the portfolio from their repository and provide that link here, it would be better.

**Comment by E-fais** [comment]
@sonalikari , i mean everyone  contributing static website must have that code in their gh repo, if they activated gh  page for their repo and provided that link in a README fiile along with their PR , anyone can see the website and  easily chsose a project as a template for their own portfolio.

**Comment by sonalikari** [comment]
Ok, Thank you

**Comment by E-fais** [comment]
Thanks
